### ISSUE TITLE
duplicate ids in different genes

### ISSUE THREAD

**Issue by diekhans** [LRGASP/lrgasp-submissions#23]
from mock submissions

One transcriptome submitted with duplicated transcripts IDs (same transcript ID in different genes IDs) → SQANTI3 failed

**Comment by FJPardoPalacios** [comment]
I tried to run SQANTI3 for Cindy's PacBio transcriptome (without expression because of the previously reported issues with the IDs), but I couldn't because 2 transcript_ids were used several times for different isoforms (all of them mapping to the chrEBV). Its path in the Drive folder is Long-read RGASP/Submissions/Cindy_submitter_id/pacbio_mod_isoforms/5-pacbio-collapse.isoforms.gtf .

The transcript_ids that gave me problems were: "m54284U_191110" and "m54284U_191111". The rest of the transcript_ids were not duplicated and they were larger e.g. "m54284U_191111_172039/99944726/ccs".

**Comment by diekhans** [comment]
GTF validations detect this problem.  thanks!!
